import barbarian from "./images/barbarian.jpg";
import mage from "./images/mage.jpg";
import thief from "./images/thief.jpg";
import alchemist from "./images/alchemist.jpg";
import knight from "./images/knight.jpg";

import mageGif from "./images/mage.gif";
import barbarianGif from "./images/barbarian.gif";
import thiefGif from "./images/thief.gif";
import alchemistGif from "./images/alchemist.gif";
import knightGif from "./images/knight.gif";

import ignoto from "./images/ignoto.jpg";
import ignotoGif from "./images/ignoto.gif";
import renekaj from "./images/renekaj.jpg";
import renekajGif from "./images/renekaj.gif";
import feticcio from "./images/feticcio.jpg";
import feticcioGif from "./images/feticcio.gif";

export const champions = [
  {
    icon: barbarian,
    avatar: barbarianGif,
    name: "Doss",
    race: "human",
    type: "player",
    classe: "barbarian",
    health: 100,
    energy: 70,
    strength: 80,
    defence: 65,
    speed: 40,
    status: "alive",
    description: "high health",
  },
  {
    icon: mage,
    avatar: mageGif,
    name: "Waltz",
    race: "human",
    type: "player",
    classe: "mage",
    health: 65,
    energy: 80,
    strength: 100,
    defence: 55,
    speed: 70,
    status: "alive",
    description: "high damage",
  },
  {
    icon: knight,
    avatar: knightGif,
    name: "Polish",
    race: "human",
    type: "player",
    classe: "knight",
    health: 80,
    energy: 80,
    strength: 60,
    defence: 95,
    speed: 40,
    status: "alive",
    description: "high defence",
  },
  {
    icon: thief,
    avatar: thiefGif,
    name: "Robbo",
    race: "human",
    type: "player",
    classe: "thief",
    health: 65,
    energy: 80,
    strength: 70,
    defence: 50,
    speed: 100,
    status: "alive",
    description: "high speed",
  },
  {
    icon: alchemist,
    avatar: alchemistGif,
    name: "Erika",
    race: "human",
    type: "player",
    classe: "alchemist",
    health: 65,
    energy: 100,
    strength: 70,
    defence: 70,
    speed: 80,
    status: "alive",
    description: "high energy",
  },
];

export const enemies = [
  {
    icon: ignoto,
    avatar: ignotoGif,
    name: "???",
    energy: "???",
    health: "???",
    strength: "???",
    defence: "???",
    speed: "???",
    status: "dead",
  },
  {
    icon: renekaj,
    avatar: renekajGif,
    name: "Renekaj",
    type: "enemy",
    energy: 100,
    health: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    status: "alive",
  },
  {
    icon: feticcio,
    avatar: feticcioGif,
    name: "Feticcio",
    type: "enemy",
    energy: 100,
    health: 100,
    strength: 100,
    defence: 100,
    speed: 100,
    status: "alive",
  },
];

// const mobs = [
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/skeletor.gif",
//     name: "Skeletor",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/nidalkaj.jpg",
//     avatar: "./images/mobs/nidalkaj.gif",
//     name: "Nidalkaj",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/feticcio.jpg",
//     avatar: "./images/mobs/feticcio.gif",
//     name: "Feticcio",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/zedaj.jpg",
//     avatar: "./images/mobs/zedaj.gif",
//     name: "Zedaj",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/drake.gif",
//     name: "Drake",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/malakaj.jpg",
//     avatar: "./images/mobs/malakaj.gif",
//     name: "Malakaj",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/hyena.gif",
//     name: "Hyena",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/abraxas.gif",
//     name: "Abraxas",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/knight.gif",
//     name: "knight",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
// ];
