export const champions = [
  {
    icon: "./images/players/barbarian.jpg",
    avatar: "./images/players/barbarian.gif",
    name: "Doss",
    classe: "human",
    type: "player",
    health: 100,
    energy: 70,
    strength: 80,
    defence: 65,
    speed: 40,
    status: "alive",
    description: "High health",
  },
  {
    icon: "./images/players/mage.jpg",
    avatar: "./images/players/mage.gif",
    name: "Waltz",
    classe: "human",
    type: "player",
    health: 65,
    energy: 80,
    strength: 100,
    defence: 55,
    speed: 70,
    status: "alive",
    description: "High damage",
  },
  {
    icon: "./images/players/knight.jpg",
    avatar: "./images/players/knight.gif",
    name: "Polish",
    classe: "human",
    type: "player",
    health: 80,
    energy: 80,
    strength: 60,
    defence: 95,
    speed: 40,
    status: "alive",
    description: "High defence",
  },
  {
    icon: "./images/players/dagger.jpg",
    avatar: "./images/players/dagger.gif",
    name: "Robbo",
    classe: "human",
    type: "player",
    health: 65,
    energy: 80,
    strength: 70,
    defence: 50,
    speed: 100,
    status: "alive",
    description: "High speed",
  },
  {
    icon: "./images/players/alchemist.jpg",
    avatar: "./images/players/alchemist.gif",
    name: "Erika",
    classe: "human",
    type: "player",
    health: 65,
    energy: 100,
    strength: 70,
    defence: 70,
    speed: 80,
    status: "alive",
    description: "High energy",
  },
];

// const mobs = [
//   {
//     icon: "./images/mobs/renekaj.jpg",
//     avatar: "./images/mobs/renekaj.gif",
//     name: "Renekaj",
//     type: "enemy",
//     energy: diceRoll(50, 100),
//     health: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/skeletor.gif",
//     name: "Skeletor",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/nidalkaj.jpg",
//     avatar: "./images/mobs/nidalkaj.gif",
//     name: "Nidalkaj",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/feticcio.jpg",
//     avatar: "./images/mobs/feticcio.gif",
//     name: "Feticcio",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/zedaj.jpg",
//     avatar: "./images/mobs/zedaj.gif",
//     name: "Zedaj",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/drake.gif",
//     name: "Drake",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/malakaj.jpg",
//     avatar: "./images/mobs/malakaj.gif",
//     name: "Malakaj",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/hyena.gif",
//     name: "Hyena",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/abraxas.gif",
//     name: "Abraxas",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
//   {
//     icon: "./images/mobs/skeletor.jpg",
//     avatar: "./images/mobs/knight.gif",
//     name: "knight",
//     type: "enemy",
//     health: diceRoll(50, 100),
//     energy: diceRoll(50, 100),
//     strength: diceRoll(50, 100),
//     defence: diceRoll(30, 80),
//     speed: diceRoll(50, 100),
//     status: "alive",
//   },
// ];
